In [2]:
import numpy as np 
import pandas as pd

In [3]:
test_array = [10, 11.5, 12, 13.5, 14,15]   
test_array[2:3]

[12]

In [4]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [5]:
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [6]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [7]:
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [8]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [12]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [13]:
np.array[‘football’]

SyntaxError: invalid character '‘' (U+2018) (3231598033.py, line 1)

In [14]:
np.array(football)

NameError: name 'football' is not defined

In [15]:
np.array[‘football’]

SyntaxError: invalid character '‘' (U+2018) (3231598033.py, line 1)

In [20]:
football=[1,2,3,4]
np.array(football)

array([1, 2, 3, 4])

In [22]:
football = [24, 235, 34, 456, 65, 67]
type(football)

list