In [1]:
import numpy as np


In [2]:
np.identity(2*2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [4]:
np.array([[9,8,7],[6,5,4],[3,2,1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [5]:
np.arange(start = 9, stop = 0, step = -1).reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
d1+1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [7]:
n6 = np.matrix([[ 1, 4, 9, 121, 144, 169], 
[ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])
np.mean(n6)

131.66666666666666

In [8]:
n1 = np.matrix([[121, 144, 169], 
[196, 225, 256], [ 289, 324, 361]])

n2 = np.matrix([[ 1, 4, 9], 
[ 1, 5, 4], [ 9, 4, 8]])

n1@n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [9]:
np.arange(20)[2:7] 

array([2, 3, 4, 5, 6])

In [10]:
np.arange(20)[0::9] 

array([ 0,  9, 18])

In [13]:
p = np.arange(20)
print(p)
print(p[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [14]:
np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])[::-1]

matrix([[9, 4, 8],
        [1, 5, 4],
        [1, 4, 9]])