# Table of Content

- NumPy in Python
- N dimensional array
- Sorting with NumPy array
- Searching with NumPy array
- Time complexity
- Indexing and Slicing
- Selection Techniques
- Pandas in Python
- Series
- Dataframe
- Indexing
- Loading and saving dataframes
- Summary

## NumPy

### Numpy Array

In [3]:
import numpy as np 

# 0-D array
new_array = np.array(40)
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

#1-D array
new_array = np.array([20,40,60,80])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

#2-D array
new_array = np.array([[20,40], [60,80]])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

#3-D array
new_array = np.array([[[20,40] ,[60,80]]])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

 
Array : 40 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 0
 
Array : [20 40 60 80] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 1
 
Array : [[20 40]
 [60 80]] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 2
 
Array : [[[20 40]
  [60 80]]] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 3


### Functions for creating numpy arrays

zeros() function

In [4]:
zeros_array = np.zeros(4, dtype=int)
zeros_array

array([0, 0, 0, 0])

In [5]:
zeros_array = np.zeros((4,2), dtype=int)
zeros_array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

ones() function

In [6]:
ones_array = np.ones((2,4), dtype=int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

empty() function

In [7]:
empty_array = np.empty([2, 2])
empty_array# 1.1e-12

array([[0.0000000e+000, 5.2150179e-310],
       [5.2150179e-310, 1.9762626e-323]])

full() function

In [8]:
full_array = np.full((2, 2), np.inf)
full_array

array([[inf, inf],
       [inf, inf]])

In [9]:
full_array = np.full((2, 2), 10)
full_array

array([[10, 10],
       [10, 10]])

zeros_like() function

In [10]:
num_array = np.arange(8)
num_array1 = num_array.reshape((4,2))
zeros_like_array = np.zeros_like(num_array1)
print(num_array)
print(" ")
print(num_array1)
print(" ")
print(zeros_like_array)

[0 1 2 3 4 5 6 7]
 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
 
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


## Sorting with Numpy array

### Quick sort

#### Using in-build sort() function

In [11]:
import numpy as np
number_array = np.array([20,4,10,8])
print(f"Before sorting : {number_array} ")
sorted_array = np.sort(number_array, kind='quick sort')
print(f"After sorting : {sorted_array} ")

Before sorting : [20  4 10  8] 
After sorting : [ 4  8 10 20] 


#### Using user defined sort function

In [12]:
def quick_sort(numpy_array):

    left_element = []
    equal_element = []
    right_element = []

    if len(numpy_array) > 1:
        pivot_value = numpy_array[0]
        for num in numpy_array:
            if num < pivot_value:
                left_element.append(num)
            elif num == pivot_value:
                equal_element.append(num)
            elif num > pivot_value:
                right_element.append(num)

        return quick_sort(left_element) + equal_element + quick_sort(right_element) #recursively call quick_sort() function
# If there exists only 1 element, then return the array    
    else:  
        return numpy_array
quick_sort(np.array([4,3,5,6]))

[3, 4, 5, 6]

#### Time and space complexity of Quick sort is best as it balances both complexities

| Time Complexity | Best | Average | Worst |
|---|---|---|---|
| Quick Sort | O(nlog(n)) | O(nlog(n)) | O(n^2) |

| Space complexity |
|---|
| O(n) |

## Searching with Numpy array

#### Using in-build searchsorted() function

In [13]:
num_array = np.array([3,4,5,6,11,12,23,11])
search_element = np.searchsorted(num_array,11) # returns the index of search element of sorted array
search_element

4

In [14]:
search_element = np.searchsorted(num_array,[11, 23, 4, 6]) # returns the list of indices of search elements
search_element

array([4, 6, 1, 3])

## Numpy Indexing and slicing

In [15]:
new_array = np.array([1,10,20,2,30,3,40,4,50,5])
new_array[1:6:2]#[start:end-1:step]

array([10,  2,  3])

### Field access

In [16]:
new_array[-3:3:-1]

array([ 4, 40,  3, 30])

In [21]:
new_array = np.array([[[1],[2],[3]], [[4],[5],[6]]])
new_array.shape
#new_array.ndim
new_array

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [20]:
new_array[1:2]

array([[[4],
        [5],
        [6]]])

### Slicing

In [22]:
new_array = np.arange(8)
new_array[slice(1,6,2)]

array([1, 3, 5])

### Advance indexing

#### Integer Indexing

In [23]:
new_array = np.array([[10, 2], [6, 4], [5, 1]]) 
print(new_array.ndim)
integer_indexing = new_array[[0,1,2], [0,1,0]] 
# row index represents row numbers, column index represnts elemets to be chosen
integer_indexing

2


array([10,  4,  5])

In [24]:
new_array

array([[10,  2],
       [ 6,  4],
       [ 5,  1]])

#### Boolean Indexing

In [25]:
new_array[new_array > 5]

array([10,  6])

In [27]:
new_array = np.array([np.nan, np.nan, 2 ,4, 6 ,10, np.nan])
new_array[~np.isnan(new_array)]

array([ 2.,  4.,  6., 10.])

## Numpy selection techniques

In [30]:
# create an array
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
# numpy.select()
np.select(condlist= [arr<5, arr>7], choicelist= [arr, arr**2])

array([  0,   1,   2,   3,   4,   0,   0,   0,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [31]:
# numpy.where()
np.where(arr < 6, arr, 2*arr)

array([ 0,  1,  2,  3,  4,  5, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [33]:
# numpy.random.choice()
#creates a uniformr random sample with np.arange() with specified size
np.random.choice(20,4)

array([ 2,  6, 19,  2])

## Pandas

### Series

In [ ]:
# create an empty series
import pandas as pd
series = pd.Series(dtype=object)
series

In [ ]:
# creating series from array
arr = np.array([20,30])
series = pd.Series(arr, copy=False)
series

In [ ]:
# creating series from dictionary
dictionary = {0: 21, 1: 400, 2: 39, 3: 10}
# keys and Series index should match, if not nan values are added
series = pd.Series(data=dictionary, index=['w', 'x', 'y', 'z'])
series

In [ ]:
# creating series from dictionary
dictionary = {'w': 21, 'x': 400, 'y': 39, 'z': 10}
# keys and Series index should match, if not nan values are added
series = pd.Series(data=dictionary, index=['w', 'x', 'y', 'z'])
series

### Series methods

In [ ]:
# describe() method
series = pd.Series([2,4,6,8,10,12])
series.describe()

In [ ]:
# count() method
series = pd.Series([2,4,6,8,10,12,np.nan])
series.count() # nan is not counted

In [ ]:
# append() method
series1 = pd.Series([10, 20])
series2 = pd.Series([40, 60], index=[2, 3])
series1.append(series2)

In [ ]:
# apply method
# lambda is one liner function
series2.apply(lambda x: x**2)

In [ ]:
# copy() method
series1_copy = series1.copy()
series1_copy

### Dataframe

Dataframe creation

In [ ]:
# creating dataframe(df) from dictionary
dictionary = {'col1': [10.0, 20.0], 'col2': [30.0, np.nan]}
df = pd.DataFrame(data=dictionary)
df

In [ ]:
# creating df from nd array
df1 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['col1', 'col2', 'col3'])
df1

In [ ]:
# creating df from list of dictionaries
list_data = [{"col1": 10, "col2": 20}, {"col1": 50, "col2": 100, "col3": 200}]
df2 = pd.DataFrame(list_data)
df2

In [ ]:
# creating df from dictionary of lists
dict_data = {"col1": [10.0, 20.0, 30.0, 40.0], "col2": [40.0, 30.0, 20.0, 10.0]}
df3 = pd.DataFrame(dict_data)
df3

### Dataframe methods

In [ ]:
# describe() method
df.describe()

In [ ]:
# count() method
df2.count()

In [ ]:
# append() method
df.append(df1)

In [ ]:
# apply method
df1.apply(lambda x: x**2)

In [ ]:
# copy() method
df1_copy = df1.copy()
df1_copy

#### Dataframe groupby method

In [ ]:
import pandas as pd
df = pd.read_csv("Week2_Groupby.csv")
df

In [ ]:
df[['Country', 'Name', 'Age']]

In [ ]:
group_df = df.groupby(by="City")['Age'].mean()
group_df

In [ ]:
# To see first values of each group
group_df.first()

In [ ]:
group_df.get_group("Pune")

In [ ]:
group_df.get_group("Nagpur")

### Pandas Indexing

In [ ]:
df4 = pd.DataFrame([[100, 2500], [490, 789], [500, 1500]],
     index=['pune', 'mumbai', 'nagpur'],
     columns=['max_speed(kmph)', 'distance(km)'])
df4

#### loc based indexing

In [ ]:
df4.loc['pune']


In [ ]:
df4.loc[['pune', 'nagpur']]


#### iloc based indexing

In [ ]:
df4.iloc[[0,2]]

In [ ]:
df4.iloc[0]

In [ ]:
df4.iloc[[0]]

## Saving and loading dataframe

### CSV data loading and saving

In [ ]:
df = pd.read_csv("Week2_Profile_Data.csv")
df

In [ ]:
df.to_csv("Week2_Profile_Data.csv")

In [34]:
np.array([1,'a',3.4, True])

array(['1', 'a', '3.4', 'True'], dtype='<U32')

In [35]:
[1,'a',3.4, True]

[1, 'a', 3.4, True]

## Happy Learning :)